# Generated by Django 2.2.6 on 2020-08-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200802_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(),
        ),
    ]
